name: Sync with remote repository
on:
  push:
    branches: [ main ]
jobs:
  sync_with_remote_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install SSH Key for remote repository
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DESTINATION_GIT_SSH_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.DESTINATION_GIT_KNOWN_HOSTS }}
        if_key_exists: replace
    - name: Push to remote repository
      run: |
          git remote add remote-repo ${{ secrets.DESTINATION_GIT_SSH_URL }}
          git push --set-upstream remote-repo
